---
title: "FRAME"
format: html
editor: visual
---

# Tablero de información sobre Calidad de Aire en Tacna

<style>
.shareagain {
  min-width: 300px;
  margin: 1em auto;
  max-width: 100%;
  position: relative; /* Para posicionar el botón en relación al contenedor */
}

.shareagain iframe {
  width: 100%;
  height: 90vh; /* Ajusta según sea necesario */
  border: 0;
  transition: all 0.3s ease; /* Añade una transición suave al cambiar el tamaño */
}

.fullscreen-button {
  position: absolute;
  top: 10px;
  right: 10px;
  padding: 5px 8px; /* Tamaño más pequeño */
  background-color: rgba(0, 128, 0, 1); /* Verde oscuro con 50% de transparencia */
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  z-index: 10; /* Asegura que el botón esté sobre el iframe */
  font-size: 0.8em; /* Tamaño de fuente más pequeño */
}

.fullscreen-button:hover {
  background-color: rgba(0, 100, 0, 0.7); /* Color más oscuro al pasar el ratón */
}

/* Estilos responsivos */
@media (max-width: 600px) {
  .fullscreen-button {
    top: 5px; /* Ajusta la posición en móviles */
    right: 5px; /* Ajusta la posición en móviles */
    padding: 4px 6px; /* Tamaño aún más pequeño */
    font-size: 0.7em; /* Ajuste de tamaño de fuente en móviles */
  }
}
</style>

<div class="shareagain" data-exeternal="1">
  <button class="fullscreen-button" onclick="toggleFullscreen()">Pantalla Completa</button>
  <iframe id="myIframe" src="https://bryan1qr.github.io/MESOMI/#datos-del-2024" loading="lazy" allowfullscreen></iframe>
</div>

<script>
function toggleFullscreen() {
  const iframe = document.getElementById('myIframe');

  if (document.fullscreenElement) {
    document.exitFullscreen();
  } else {
    iframe.requestFullscreen().catch(err => {
      console.log(`Error al intentar entrar en pantalla completa: ${err.message}`);
    });
  }
}
</script>
